version: '3'
services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root      
    ports:
      - "5432:5432"
    volumes:
      # - ./sql/database-initial.sql:/docker-entrypoint-initdb.d/database-initial.sql   
      - ./postgres-data:/var/lib/postgresql/data

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "go@devbean.com.br"
      PGADMIN_DEFAULT_PASSWORD: "12356"
    ports:
      - "54321:80"
    depends_on:
      - postgres